<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>SpoolDatTorrent.Web</RootNamespace>
		<AssemblyName>SpoolDatTorrent.Web</AssemblyName>
		<Version>0.1.0</Version>
		<BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MudBlazor" Version="9.8.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\spool-dat-torrent.core\spool-dat-torrent.core.csproj" />
	</ItemGroup>

</Project>
