// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpoolDatTorrent.Core.Data;

#nullable disable

namespace SpoolDatTorrent.Core.Data.Migrations
{
    [DbContext(typeof(SpoolDbContext))]
    partial class SpoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("SpoolDatTorrent.Core.Models.TorrentFileItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMatchedByDat")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelectedForDownload")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TorrentStreamItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileIndex");

                    b.HasIndex("Status");

                    b.HasIndex("TorrentStreamItemId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("SpoolDatTorrent.Core.Models.TorrentStreamItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CachedDatPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("CachedTorrentPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileFilter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MovedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalDatPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalMagnet")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTorrentPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpoolingTargetOverride")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strategy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TorrentIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TorrentIdentifier");

                    b.ToTable("Streams");
                });

            modelBuilder.Entity("SpoolDatTorrent.Core.Models.TorrentFileItem", b =>
                {
                    b.HasOne("SpoolDatTorrent.Core.Models.TorrentStreamItem", null)
                        .WithMany("Files")
                        .HasForeignKey("TorrentStreamItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpoolDatTorrent.Core.Models.TorrentStreamItem", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
