<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>SpoolDatTorrent.Core</RootNamespace>
		<AssemblyName>SpoolDatTorrent.Core</AssemblyName>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BencodeNET" Version="5.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.0" />
	</ItemGroup>

</Project>
